### ISSUE TITLE
Losing session state of integer values

### ISSUE THREAD

**Issue by apregister08** [stoiveyp/Alexa.NET.StateManagement#8]
It appears the session state of integer values are dropping during round trips between the Alexa device and the Lambda function.   It appears to be working fine for string values.

Examples

BEFORE
--------
skillState.SetSession("fruit", "apple");
skillState.SetSession("number", 100);

return ResponseBuilder.Tell(new SsmlOutputSpeech { Ssml = $"<speak>{speech}</speak>" }, skillState.Session);

AFTER
-------
var fruit = skillState.GetSession<string>("fruit");  //  fruit = "apple"
var number = skillState.GetSession<int>("number");  // number = 0

**Comment by stoiveyp** [comment]
Absolutely right - code had an issue where strings and complex objects were fine, but other value types didn't work correctly.

I've added a test for this, fixed the code in #9, and it's now available in v2.0.4

https://www.nuget.org/packages/Alexa.NET.StateManagement/2.0.4

**Comment by apregister08** [comment]
Works perfect.  Thanks a lot!
